{
 "title": "RedisManagerDashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis Connection Latency Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_connection_latency_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Redis Connection Latency Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "redis_connection_latency_seconds_count",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Redis Connection Latency Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "redis_connection_latency_seconds_sum",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Redis Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "redis_pool_size", "legendFormat": "Total Pools" }
   ]
  },
  {
   "title": "Redis Pool Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "redis_pool_active", "legendFormat": "Active Connections" }
   ]
  },
  {
   "title": "Redis Pool Unhealthy Pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "redis_pool_unhealthy", "legendFormat": "Unhealthy Pools" }
   ]
  },
  {
   "title": "Redis Pool Idle Pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "redis_pool_idle", "legendFormat": "Idle Pools" }
   ]
  }
 ]
}