version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: testbench/Dockerfile
    volumes:
      - ./testbench/app:/usr/src/app
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./testbench/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./testbench/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./testbench/grafana/dashboards:/var/lib/grafana/dashboards
      - ./testbench/grafana/provisioning:/etc/grafana/provisioning
      - ./testbench/grafana/config/grafana.ini:/etc/grafana/grafana.ini

    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

